### ISSUE TITLE
Release in Jade?

### ISSUE THREAD

**Issue by davetcoleman** [catkin/catkin_tools#135]
Just curious the timeline on this powerful tool. I've started to convert other guys in my lab to using this build method but its future is unclear to me.

**Comment by dirk-thomas** [comment]
Since it is a Python package its release will be cross-distro. The question is when do we want to "recommend" its usage?

**Comment by davetcoleman** [comment]
Yea, that's what I mean. When should it be announced. Jade seems like a good time to do it.

**Comment by wjwwood** [comment]
We have a roadmap: https://github.com/catkin/catkin_tools/issues/90

But there is no timeline because I've run out of time to work on it for now. I wanted to finish up the things in that issue and then start writing tutorials which used this tool, `package.xml` format 2, and something like `catkin_simple`. There just isn't time enough in the day.

I've gotten a lot of help from you guys in the form of feature enhancements and bug reports, but until we can get a concerted effort to push towards what I described above, I think it will continue to be delayed.

**Comment by jbohren** [comment]
> The question is when do we want to "recommend" its usage?

As soon as we can.

I've already been recommending people use `catkin build` over `catkin_make`. I've only had positive feedback.

As far as I can tell, nothing has been done towards resolving everything in #90 and besides the compiler warning and shell-completion, none of those issues really important to me.

**Comment by wjwwood** [comment]
@jbohren some of the issues in #90 are more trivial or niche, but these are potential bug producers:

- build: test for topological ordering with underlays (#30)
- Installed libraries reference devel space (#70)

They are critical before I would consider recommending `catkin build` over `catkin_make_isolated` to anyone other than experienced developers. I agree it would be good to get it out as soon as possible, but again, it takes time and I'm up to my eye balls in backlogged ROS 1 issues as is.

**Comment by jbohren** [comment]
@wjwwood If this is going slowly, at least we should make a "beta" release, and get it out into the wild. That will generate a good deal of feedback and find any potential issues before we tell everyone to switch.

**Comment by jack-oquin** [comment]
My impression is that catkin_tools is plenty good enough for the beta release Jon suggests.

**Comment by wjwwood** [comment]
@jbohren @jack-oquin I announced this to a few of the SIG's, I guess you guys mean an email to ros-users? I'm fine with that, but maybe it would be good coming from someone other than me. After all, I've not been the only one working on it.

I don't mind a larger group of people using it as long as they understand that there may still be some rough edges. Unlike `catkin_make` and `catkin_make_isolated`, I've been trying to get it "right" rather than done sooner. The existence of both of those tools was blocking the release of Groovy, so it was a different situation.

**Comment by jbohren** [comment]
> @jbohren @jack-oquin I announced this to a few of the SIG's, I guess you guys mean an email to ros-users? I'm fine with that, but maybe it would be good coming from someone other than me. After all, I've not been the only one working on it.

Well I doubt many people will want to try it out a new build tool until after the IROS deadline. So I say we broadcast to ROS Users at the end of the month. How does that sound?

> I don't mind a larger group of people using it as long as they understand that there may still be some rough edges. Unlike catkin_make and catkin_make_isolated, I've been trying to get it "right" rather than done sooner. 

When we announce it I'm fine calling it a beta and emphasizing that people should give feedback.

I think the announcement should cover not just `catkin_tools` but also `package.xml` format 2, and maybe even `catkin_simple`.

**Comment by jack-oquin** [comment]
Announce it whenever you guys think best.

I like to use catkin build myself, but find myself using catkin_make when working with people in the UTexas CS robotics lab, because catkin build is not "supported", and hence I am reluctant to recommend using it.

I agree that package.xml format 2 could use some more publicity and encouragement.

I have doubts about catkin_simple, unless someone has agreed to support it.

**Comment by jbohren** [comment]
@davetcoleman Is it ok to close this for now? The immediate roadmap goal is to release Beta 2 (0.4.0) in the next couple of months. Recommending this tool over `catkin_make` won't happen until everything in #90 is resolved.

**Comment by davetcoleman** [comment]
Perhaps before closing this we could add a sentence to the home page of https://catkin-tools.readthedocs.org/en/latest/ explaining its roadmap?

**Comment by jbohren** [comment]
> Perhaps before closing this we could add a sentence to the home page of https://catkin-tools.readthedocs.org/en/latest/ explaining its roadmap?

I think the only thing that can be said with certainty about the roadmap is what's in the GitHub Milestones: https://github.com/catkin/catkin_tools/milestones

Maybe we could just add a link from the documentation to that page?

**Comment by davetcoleman** [comment]
Done https://github.com/catkin/catkin_tools/pull/262
