### ISSUE TITLE
configuration option to make "catkin build" work like --only-pkg-with-deps 

### ISSUE THREAD

**Issue by dustingooding** [catkin/catkin_tools#148]
I'm in the habit of using catkin_make's "--only-pkg-with-deps" argument to ensure I get a fully-populated workspace: both build_depends and exec_depends for a given package.  When I run "catkin build package_name", package_name's exec_depends aren't built, though.  This makes it problematic to use, as my package isn't functional until its exec_depends are present.  (Or am I missing something or doing something wrong?)

**Comment by wjwwood** [comment]
Hmm, I think your run dependencies should be built in this case. It might be a bug.

**Comment by jbohren** [comment]
@dustingooding Do you have any time to add a simple unit test which reproduces this problem? You can see some of the existing test infrastructure here: https://github.com/catkin/catkin_tools/tree/master/tests

**Comment by wjwwood** [comment]
We continued the discussion here:

https://github.com/catkin/catkin_tools/issues/224#issuecomment-127688809

I think the consensus is that we need an option to control if the run dependencies of a specified package are built in addition to the package itself. The other question is if this should be the default behavior and you can opt-out or if it should be opt-in.

**Comment by jack-oquin** [comment]
I agree that building ``<exec_depend>`` packages is intuitively attractive when building a bunch of packages from source. It makes metapackages useful for building a diverse set of things.

From that perspective, the build farm can easily opt-out to get the current behavior, and the default could be tailored towards programmers building from source.

**But**, isn't the old ``<run_depend>`` also used for transitive build dependencies (like a ``<build_export_depend>``)? In that case, maybe it *is* sometimes needed for building. I have always found that confusing, so maybe I am mixing it up, again.

 * http://www.ros.org/reps/rep-0140.html#removing-run-depend

**Comment by wjwwood** [comment]
>  In that case, maybe it is sometimes needed for building.

I do not think that is the case. Whether a old style `<run_depend>` is an `<exec_depend>` or a `<build_export_depend>` or both, it is not needed to build a package. But the `<run_depend>`'s of a package's `<build_depend>`'s are needed to build it, because they might be `<build_export_depend>`'s. The question at hand is whether or not to build a target package's `<run_depend>`'s after building it so that it can also be run.

**Comment by roehling** [comment]
I'd consider `<exec_depend>`s to be "soft" dependencies, meaning they should be built, but they don't imply any particular build order. It might be useful to have an option that makes missing `<exec_depend>`s a non-fatal condition (e.g. for build servers), but most users will need them.

**Comment by wjwwood** [comment]
> I'd consider <exec_depend>s to be "soft" dependencies, meaning they should be built, but they don't imply any particular build order.

I'd argue that they should only be built if you need to run the package afterwards (which is probably a good default, and the build farm can explicitly turn this off), and I'd also argue that they do affect the build order in that they should be built after the package which run depends on them if possible. That way you don't accidentally hide bugs where a package is actually a build depend, but isn't listed as one.

> It might be useful to have an option that makes missing <exec_depend>s a non-fatal condition (e.g. for build servers), but most users will need them.

I don't understand what you mean here. Even "missing" build dependencies are not errors, since they may be in another workspace or they may be system dependencies which cannot be easily detected.

**Comment by roehling** [comment]
I understand your point regarding the build order, although in my opinion, the likely build time savings by exploiting parallelism win over the potentially masked dependency bugs. 

I always assumed that missing (in the sense that they are not accessible by the build environment) build dependencies would be a fatal condition, since the build will fail without them by definition. But I did not consider that the presence of system dependencies is a bit tricky to verify.

**Comment by jbohren** [comment]
@wjwwood Is there any reason why we shouldn't build `exec_depend`s along with `build_depend`'s?

**Comment by mikepurvis** [comment]
I agree with what I believe is being said here:
- Packages which are an `<exec_depends>` should definitely build by default when you `catkin build foo_package`, so that the result is a runnable workspace.
- There should be a config flag to allow you to opt-out of this behaviour, in you're doing packaging or otherwise managing this yourself.
- If run depends are missing at build time, it should be a post-build notice, eg "WARNING: X built successfully, but may not run due to missing exec dependencies: Y, Z".

As far as the behaviour of a plain `catkin build`, I feel a warning is still entirely appropriate in this scenario, as the user is still very much capable of getting themselves in a situation where they've built packages that are not capable of running.

**Comment by jbohren** [comment]
@mikepurvis Yeah, I'm with you on all points above.

I think in general, people expect to be able to run products in a workspace after building them. There might be some cases where people just want to make sure things build, though. We could add a configuration option which means build "dependencies required to build" or only build "dependencies required to run". I think it should be set to what is required to run by default.

It could be switched with the following (multiple allowed):
* `--deps all` - Include all deps except `doc_depend` [default]
* `--deps build` - Include `build_depend`, `buildtool_depend`, `build_export_depend`, and `buildtool_export_depend`
* `--deps test` - Include `build` deps (above) and `test_depend`
* `--deps run` - Include `test` deps (above) and `run_depend`, `exec_depend`
* `--deps doc` - Include `doc_depend`

**Comment by jack-oquin** [comment]
+1 sounds good to me

**Comment by mikepurvis** [comment]
:+1:

**Comment by jbohren** [comment]
> `--deps all` seems a bit of a misnomer if it's not actually all. I might say make that `--deps exec`, and if `--deps all` is included, make it truly be all.

Right, `--deps run` could just be the default, and `--deps all` could really be all (`run` + `doc`).

**Comment by jack-oquin** [comment]
I prefer ``--deps exec`` instead of ``--deps run``. The old ``<run_depend>`` tag was hopelessly confusing, and that option name inherits those problems.

Implicitly including other dependencies is also confusing. The format 2 dependency names were finally accepted after almost a year of discussion. They are all basically orthogonal. Since multiples are allowed, it seems less confusing to make that explicit, like: ``--deps build --deps test --deps exec``. 

``--deps all`` is clearly useful to save keystrokes. I agree with Mike that it should be truly all.

**Comment by jbohren** [comment]
> I prefer `--deps exec` instead of `--deps run`. The old `<run_depend>` tag was hopelessly confusing, and that option name inherits those problems.

I'm fine making it consistent.

> Implicitly including other dependencies is also confusing. The format 2 dependency names were finally accepted after almost a year of discussion. They are all basically orthogonal. Since multiples are allowed, it seems less confusing to make that explicit, like: `--deps build --deps test --deps exec`.

The orthogonality is fine for dependency resolution, but since this situation actually involves building, it's impossible to build `exec_depend` packages without their own `build_depend` packages.

We could disallow multiples and have the following options:
* `--deps build` - Only build `build_depend`, `buildtool_depend`, `build_export_depend`, and `buildtool_export_depend`
* `--deps test` - Only build `build` deps (above) and `test_depend`
* `--deps exec` - Only build `test` deps (above) and `run_depend`, `exec_depend` **[default]**
* `--deps doc` - Only build `doc_depend`
* `--deps all` - Include all deps

**Comment by jack-oquin** [comment]
Why disallow multiples, Jon?

**Comment by jbohren** [comment]
> Why disallow multiples, Jon?

Except for `--deps doc` which could be useful for generating documentation for a workspace without building it, the other options listed above each extend the previous one, so multiples wouldn't have any effect.

**Comment by mikepurvis** [comment]
I'd just as soon keep it simple unless there's a really compelling reason to do otherwise.

**Comment by jbohren** [comment]
> I'd just as soon keep it simple unless there's a really compelling reason to do otherwise.

Yeah, the simplicity doesn't hurt, either.

**Comment by mikepurvis** [comment]
I don't have a sense what's involved in implementing this. Is it a significant undertaking?

**Comment by jbohren** [comment]
> I don't have a sense what's involved in implementing this. Is it a significant undertaking?

No, it's pretty easy. We add a configuration option to the `catkin_tools.Context` class, and then just make sure the appropriate dep-inclusion function gets passed to [`catkin_tools.common.get_recursive_build_depends_in_workspace`](https://github.com/catkin/catkin_tools/blob/fc3319776fa0660b993f90ea345100fc4408170f/catkin_tools/common.py#L257).

**Comment by wjwwood** [comment]
I agree with most everything in https://github.com/catkin/catkin_tools/issues/148#issuecomment-174561935. However, there are two differences that should be made in my opinion:

- `build[tool]_export_depend` tags should be included in `--deps exec` but not `--deps build`
 - The rational being that a package should build even if its `build[tool]_export_depend` dependencies are not there.
- `--deps test` should be a super set of `exec` (`exec` + `test_depend` tags)
 - This might mean that `--deps test` should be the default and not `--deps exec`

**Comment by dustingooding** [comment]
I agree with @wjwwood on his proposed mods, esp the test one.  If you're building from source, there's a high probability that you're actively developing, and thus building/running tests is expected.

**Comment by jbohren** [comment]
@wjwwood Ok, I recognize there's more subtlety about  the `export` depends but if you want to avoid building more than you have to, isn't it more complex than that. For example, if you have packages A, B, and C, such that C has a `build_depend` on B and B has a `build_export_depend` on A. If you run `catkin build C`, then you need to build all three, right?

For the second point, it sounds like you just want to switch the cardinality of `--deps exec` and `--deps test`. I.e.:
 * `exec = build_depend + exec_depend`
 * `test = build_depend + exec_depend + test_depend` **(default)**

**Comment by wjwwood** [comment]
In the situation you described that's always the case. When calculating the packages to build in order to build any single package, you need that package's direct build dependencies and then the "run" (build export + exec) dependencies of those direct build dependences, recursively.

You do not, however, need the build export or exec dependencies of the package you asked the tool to build. What's in question here is whether or not to include them by default since you likely want to do more than just build a package when using the tool locally (you will immediately want to run its tests or run its executables).

For a more complex example:

- A build depends on B
- A build export depends on C
- A exec depends on D
- B build depends on E
- B build export depends on F
- B exec depends on G
- F build export depends on C

If you run:

- `catkin build B --deps build` you should get a build order of `E B`
- `catkin build B --deps exec` you should get a build order of `E B F G`
- `catkin build A --deps build` you should get a build order of `E B F C G A`
 - In this case E is before B, because in order to build B you need E, but if you consider what A should source before building it would be `B F G`
 - C comes in because F build export depends on it and the "run" depends of F need to be there before building A since A build depends on it.
 - C and G could be swapped I think (parallel)
- `catkin build A --deps exec` you should get a build order of `E B F C G A D`

---

For the second point, yes that's it exactly.

**Comment by jbohren** [comment]
> You do not, however, need the build export or exec dependencies of the package you asked the tool to build.

Right, so in all of this, you need two specifications: 
1. which of the first-order deps to include
2. which of the second+-order deps to include

---

- `catkin build A --deps build` you should get a build order of `E B F G`

Why do the `exec` and `export` depends get placed after `B` in this order? Is there a reason this can't be `E F G B`?

**Comment by wjwwood** [comment]
You could have either order, but I would slightly prefer the former since it could expose a bug where the package uses a "run" depend to build but doesn't declare it as a build dependency. It could still be hidden if one of the "run" depends gets put before the actual package being built because one of the package's build dependencies depend on it.

**Comment by wjwwood** [comment]
In the context of the example, if B actually should have had a build depend on F then for the two build orders:

- `E B F G`: B would fail to build since F isn't there yet (correct behavior)
- `E F G B`: B would possibly build successfully (incorrect behavior; hidden/subtle bug)

**Comment by jbohren** [comment]
>  I would slightly prefer the former since it could expose a bug where the package uses a "run" depend to build but doesn't declare it as a build dependency.

I see. In this sense, then, `exec_depends` and `*export_depends` are actually reverse edges in the dependency graph?

**Comment by wjwwood** [comment]
Yeah.

**Comment by jbohren** [comment]
>>> I would slightly prefer the former since it could expose a bug where the package uses a "run" depend to build but doesn't declare it as a build dependency.

>>I see. In this sense, then, exec_depends and *export_depends are actually reverse edges in the dependency graph?

> Yeah.

Right, then.

**Comment by roehling** [comment]
+1 for the proposed semantics

If  `--deps test` is going to be the default (which I very much support), maybe there should be a `--no-deps` or `--deps none` option for people who insist on the current way `catkin build` behaves.

**Comment by jbohren** [comment]
> If  `--deps test` is going to be the default (which I very much support), maybe there should be a `--no-deps` or `--deps none` option for people who insist on the current way `catkin build` behaves.

Well, there's already a `--no-deps`, that would definitely remain. Since these are mutually exclusive, it might be reasonable to have the following, which could be both a `catkin config` option and a per-invocation `catkin build` option:

- `--no-deps`
- `--doc-deps`
- `--build-deps`
- `--exec-deps`
- `--test-deps` *[default]*
- `--all-deps`

**Comment by mikepurvis** [comment]
This seems like something which should be set once, in the workspace config. How likely is it to vary from build to build? My sense is not very.

**Comment by jbohren** [comment]
> This seems like something which should be set once, in the workspace config. How likely is it to vary from build to build? My sense is not very.

Well `--no-deps` is an option which should be available per-call. For consistency, the others should be, too.

**Comment by roehling** [comment]
Would it make sense to separate the `--deps`/`--no-deps` switch from a `--deps-type` option? Because the current naming scheme is slightly misleading (`--test-deps` does not only include test depends).

**Comment by jbohren** [comment]
> Would it make sense to separate the `--deps`/`--no-deps` switch from a `--deps-type` option? Because the current naming scheme is slightly misleading (`--test-deps` does not only include test depends).

Let's let this sit for a bit, and we can discuss the exact interface when someone is ready to implement it. For now I think the plan for 0.4.0 is to add `exec_depends` to the recursive deps which are built, in order to solve OP's problem.

> [The Two Hard Things](http://thecodelesscode.com/case/220)

> A junior monk said to master Kaimu: One of the Patriarchs claimed that there are “only two hard things” in our craft. What are these “two hard things”?

>Kaimu answered: You only need to remember that the first hard thing is called “cache invalidation”.

>The junior monk asked: Does that mean that a whole cache is made invalid, or just some of its elements? And why call it “invalidation” when the only error is that the data is stale? Wouldn’t “cache element expiration” be a better name?

>Kaimu answered: Now you know the second hard thing.

**Comment by mikepurvis** [comment]
For anyone else like me who is in a big hurry and just needs a dirty fix: c8e139ff57d84c2e0ee7a13d9dc10d8ae1127652

**Comment by jbohren** [comment]
@mikepurvis Thanks for cutting through that. I'm going to add something similar to c8e139f on the current 0.4.0 dev branch, https://github.com/catkin/catkin_tools/tree/pre-0.4.0-linked-devel (#276)

**Comment by mikepurvis** [comment]
I tried `pre-0.4.0-linked-devel` again, and it's now building catkin correctly, but not pulling in nearly as many packages to build as my quick & dirty fix does.

**Comment by jbohren** [comment]
> I tried` pre-0.4.0-linked-devel` again, and it's now building catkin correctly, but not pulling in nearly as many packages to build as my quick & dirty fix does.

Do you mean it's not pulling in the run and exec dependencies that it should be?

**Comment by mikepurvis** [comment]
I don't believe so, but I'd need to look more closely at exactly what's going on.

The workspace contains 350 packages across 97 repos. My hack builds 191 of them, and the current `pre-0.4.0-linked-devel` builds around 140.

**Comment by jbohren** [comment]
> The workspace contains 350 packages across 97 repos. My hack builds 191 of them, and the current pre-0.4.0-linked-devel builds around 140.

So the difference is that c8e139f preserves `master`'s inclusion of run-deps of build-deps of requested package, whereas `pre-0.4.0-linked-devel` includes run-deps of the requested package, but not the run-deps of the build-deps of the requested package.

**Comment by jbohren** [comment]
@mikepurvis The latest `pre-0.4.0-linked-devel` 6bc286a should give the same deps as your c8e139f.
