### ISSUE TITLE
workspace specific config

### ISSUE THREAD

**Issue by tprk77** [catkin/catkin_tools#218]
This is question, and possibly an enhancement.

A little background: My company is currently using `catkin_make`, and I'm investigating using `catkin_tools`. We have a top-level `CMakeLists.txt` which we modified to set some flags, specifically turning on C++11 for the entire workspace. Obviously that doesn't work with catkin tools.

My initial thought was to do something like this:

    $ catkin config --cmake-args -DCMAKE_CXX_FLAGS=\"-std=c++11\"

And then commit the `.catkin_tools` directory to version control. But I'm not sure that was the right thing to do. Git keeps telling me that `config.yaml` has been modified when I don't really care.

Is there any way to set workspace specific options, and check those into VC, without messing with the user's ability to manage config? For example, we want to save the C++11 flags, but still let the user set the `-j` and `-p` flags depending on how many cores they have.

Or maybe there is some other way to achieve this behavior? Any advice would be great.

**Comment by tprk77** [comment]
(Oops, hit submit early by accident. Edited.)

**Comment by jbohren** [comment]
@tprk77 Committing the `.catkin_tools` directory to version control is a reasonable thing to do. Is it actually saying that `default/config.yaml` is changing, or is `default/build.yaml` is changing? If it's the latter, then it would be reasonable to add `default/build.yaml` to your `.gitignore` since it just captures the last values used to build, but unless someone runs `catkin config ...` the `default/config.yaml` file shouldn't change.

**Comment by wjwwood** [comment]
I don't know whether or not committing the configurations is a good idea or not. I guess it depends on your use case.

However, for the use case you've described here, you definitely need to set the C++11 compiler flags as part of you package's CMake code and not as a configuration of the build tool. Because if someone else gets your packages and wants to build them one by one or with a different tool then it will not work.

The easiest thing to do would be to just put something like this in all of your package's `CMakeLists.txt`:

```cmake
if(NOT WIN32)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -Wall")
endif()
```
https://github.com/ros2/examples/blob/1e367ff5c099e12a1b2c2b9d6c01180a92d3046b/rclcpp_examples/CMakeLists.txt#L5-L7

Though the check would ideally be more specific w.r.t. compiler name and version, but the above will work for modern versions of gcc and clang.

The more correct thing to do would be to set this in any package which uses C++11 in its C++ files, and export this using a cfg extras file for any packages which install headers which use C++11 stuff.

**Comment by tprk77** [comment]
@jbohren Yes, `default/config.yaml` is changing because I'm saving other build flags. In my case, I saved the C++11 flags (as above), and committed it, but then someone else did something like:

    $ catkin config -j 4

Which modifies the file, but it's not something they want to commit.

Now that you mention it, `default/build.yaml` is changing, but I'm not worried about that, I'll just put it in the `.gitignore` and remove it.

@wjwwood What you're saying makes sense, for sure, but I was hoping to avoid editing every `CMakeLists.txt`. We have many, and that ends up being alot of boilerplate. We set a couple other flags, too. But maybe it's unavoidable. Is there any way to simulate a top-level `CMakeLists.txt`? Or is that concept incompatible with catkin tools?

I guess my company's usage is a little different because we ended up using one big Git repo for the entire workspace. It's more standard to put every package in its own repo, right?

**Comment by wjwwood** [comment]
There is no equivalent to the "top level CMakeLists.txt" in catkin_tools (and it is not recommended to override that in `catkin_make` either). It has less to do with repo management and more to do with the fact that not all the packages are necessarily cmake packages. You could just as easily have a build type for autotools or plain make or gradle, which would render the any CMakeLists.txt contents useless. That's why the configuration of catkin tools has cmake specific args and make specific args.

You can do what ever works best for your company, but if you truly want your packages to be decoupled from each other you have to think about how you'd build them one at a time, by themselves. And in that case, you will want them to be self contained as much as possible and therefore set things like compiler flags on packages which need them and not on ones that don't and pass them along to other packages when you install something that requires the flags. That being said, if you never intend to reconfigure your workspace of packages or share parts of your set of packages with others (who might not share your global configurations) then none of that matters I guess.

**Comment by tprk77** [comment]
I talked to my coworkers some more, and we are considering two options:

  1. Continue having `.catkin_tools` under version control
  2. Create a company CMake module, and include it in each package

For option 1, I am thinking about removing the default profile from version control, and instead committing a release and debug profile. If a user wants a custom config, they can copy a profile.

```bash
$ catkin profile list
[profile] Available profiles:
- debug
- release
$ catkin profile add default --copy debug
[profile] Created a new profile named default based on profile debug
[profile] Available profiles:
- default (active)
- debug
- release
$ catkin config -j 4
...
```

Option 2 seems to be a good compromise and bit cleaner. We can maintain one file for all our common CMake flags. The only thing I'm not sure about, is the best way to setup `CMAKE_MODULE_PATH`.

**Comment by rsarrazin2** [comment]
The solution here: Having the raw `.catkin_tools` folder (i.e. the state after `catkin clean`) under source control and having the full folder in `.gitignore`.

When a change needs to be done to the config: Remove locally from `.gitignore`, do the change, stage the change (but not `.gitignore`), discard the change to `.gitignore`, commit.

**Comment by timonegk** [comment]
In order to avoid changing the gitignore file every time, you can use `git add -f path/to/file` which can also add ignored files.

**Comment by mikepurvis** [comment]
Can't most of this be achieved with the profiles feature of catkin_tools? It's pretty unconventional to check your whole workspace into source control.
