### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS fails if the build target directory already exists

### ISSUE THREAD

**Issue by markisus** [catkin/catkin_tools#227]
I need to generate a compile_commands.json for my package so I ran `catkin build mypkg -DCMAKE_EXPORT_COMPILE_COMMANDS=ON` but this did not generate the compile_commands.json file like I expected. I think this was because the target directory already existed because when I deleted the target directory (build/mypkg), the file was generated

**Comment by wjwwood** [comment]
The question is whether or not CMake was run again. Deleting the build folder for that package would force CMake to run again.

This could indicate a bug in the configuration management which does not retrigger CMake when the CMake variables have changed.

**Comment by markisus** [comment]
Could it be here?

https://github.com/catkin/catkin_tools/blob/master/catkin_tools/verbs/catkin_build/build.py#L102

**Comment by wjwwood** [comment]
I don't think so. It's not that your package is not being processed, it is just that it is skipping CMake because it has been previously run. See: https://github.com/catkin/catkin_tools/blob/master/catkin_tools/verbs/catkin_build/job.py#L188-L200

**Comment by markisus** [comment]
You're right, running `catkin build --force-cmake mypkg` generates `compile_commands.json`

**Comment by IanTheEngineer** [comment]
I think this issue is related to the quirkiness that I am experiencing: simply recompiling a previously built `catkin_tools` workspace with the cmake debug flag, `-DCMAKE_BUILD_TYPE=Debug`, does not generate debug symbols for the executables previously built, if nothing else has changed in the source code. Blowing away the `build` and `devel` directories does the trick. Not sure if this is intended behavior, so I figured I'd mention it here.

**Comment by jbohren** [comment]
This is a usability issue, if the CMake arguments change between builds, `catkin build` should infer that the user wants to force CMake to run again.
