### ISSUE TITLE
How to separate the build and install steps

### ISSUE THREAD

**Issue by mikepurvis** [catkin/catkin_tools#234]
Right now:

```
catkin config --install-space /opt/ros/indigo
catkin build
...
catkin --install
sudo catkin build
```

Gets you this:

```
Error: Attempting to build a catkin workspace using build space: "..." but that build space's 
most recent configuration differs from the commanded one in ways which will cause problems.
Fix the following options or use `catkin clean -b` to remove the build space: 
 - install: False (stored) is not True (commanded)
```

In ros-install-osx, the desire not to run the entire build as root is dealt with by simply having `/opt/ros/foo` owned by the user rather than root, so everything is as the user (following the Homebrew model). But there are packaging and other use cases where separating the build and install steps is desirable. Is there truly something dangerous being blocked here, or does is it getting caught in a dragnet of potentially dangerous behaviours?

If the latter, can we put in an exemption that allows running just the install step on an already-built workspace?

**Comment by wjwwood** [comment]
There's no good way to do this. I thought we discussed this at some point but I could not find the related issue.

Basically the conclusion was that any privilege escalation would need to be done by the tool and the tool should never be run as root. So basically you'd do something like `catkin config --sudo-install; catkin build` and each `make install` would be prefixed with `sudo ` by the tool and the you'd have to type in your password the first time it came up. Something more elegant is probably possible, but I'm not sure exactly what that looks like.

**Comment by wjwwood** [comment]
Well it correctly warns you that building it without `--install` and then re-building it with `--install` may fail in unexpected ways. The first time goes like this:

- build pkg A without installing it
- source devel space of A
- build pkg B (which depends on A) without installing it
- etc...

The second time (if it let you) you'd get:

- build pkg A, installing this time
- source install space of A
- build pkg B (which depends on A), installing this time
- etc...

The problem with that is pkg B may not rebuild it's binaries and libraries since no build configs or source files changed (even if you force a re-run of CMake), but the libraries it should link against have changed (which would break usage of `RPATH` for example), and ever generated code might reference the wrong thing (devel space of previous packages rather than their install spaces). So it's best, when changing that option, to rebuild everything after cleaning.

The root issue, as I see it, is that you want to introduce the `--install` after building so you can do that as `root`, but that's just not a good idea in my opinion because any other files created by the tool will then be owned by root. `make` does a pretty good job of avoiding this, but it's still problematic with tools like `pip` and others.

**Comment by mikepurvis** [comment]
Got it— I understand the issue.

**Comment by foodtooth** [comment]
Hi, is there anything new about this issue, or do I have to implement that "--sudo-install" option?
