### ISSUE TITLE
How to pass "--gtest_filter=TestSuiteName.TestName" to catkin run_tests?

### ISSUE THREAD

**Issue by StephanOpfer** [catkin/catkin_tools#269]
Hi all,

Is there an option to pass "--gtest_filter=TestSuiteName.TestName" correctly, in order to execute only one specific test?

Greetings,
  Stephan

**Comment by jbohren** [comment]
If `--gtest_filter` is normally passed to `make run_tests`, then the following should work:

```bash
catkin run_tests --make-args --gtest_filter=TestSuiteName.TestName
```

**Comment by StephanOpfer** [comment]
It is a simple command line argument for gunit-test executables. 
So ./testExec --gtest_filter=TestSuiteName.TestName works. 

The questions is: How to pass command line arguments to an executable that is started by catkin run_tests?

**Comment by wjwwood** [comment]
This website suggests using `rosrun`: https://personalrobotics.ri.cmu.edu/software/unit-testing

I'd need to experiment with the options a little, but I think it should be possible to pass them through. However, the approach may not be the best since, inherently anything you give to catkin tool's command line will be passed to all packages and all calls to make or whatever. So it should really be used in conjunction with `<package name> --no-deps`.

For me personally I open a new shell, source the test shell file and run the test directly from the build space. Which is really similar to the approach in the above link (using `rosrun`).

**Comment by jbohren** [comment]
@StephanOpfer alternatively can you use the `GTEST_FILTER` environment variable?

**Comment by StephanOpfer** [comment]
The rosrun option seems comfortable to me. I choose this. 

Thanks for the option.

**Comment by jbohren** [comment]
>  I choose this.

![grail](https://cloud.githubusercontent.com/assets/1253450/12251548/c6fceac8-b89d-11e5-881c-773e86374c0b.gif)
