### ISSUE TITLE
Clarify metapackage dependency behavior.

### ISSUE THREAD

**Issue by jbohren** [catkin/catkin_tools#366]
Currently, if a user's package depends on a metapackage (such as `fanuc`), `catkin build` displays an error similar to the following:

```
Abandoned <<< fanuc_motion             [ Depends on unknown jobs: fanuc ]
```

This is in accordance with [REP-140](http://www.ros.org/reps/rep-0140.html#metapackage), which says the following with respect to metapackages:

> They cannot be used for catkin builds and compile nothing themselves. 

Except apparently `catkin_make_isolated` builds metapackages and packages which are linked only by `<exec_depend>` dependencies.

So we should either allow or disallow depending on metapackages for building. If we allow it, we need to patch the `build` verb, and if we continue to disallow it, we need to make this error message clearer so people know it's because they're depending on metapackages.

Related discussions: #364 #224 #148

**Comment by jack-oquin** [comment]
Does ``catkin_make`` allow ``<exec_depend>`` on metapackages, too?

If so, maybe REP-0140 should be amended to allow that behavior, and ``catkin build`` should support it, too. It does make intuitive sense to allow such dependencies. I believe it was ruled out only due to difficulties with building.

**Comment by gavanderhoorn** [comment]
>  It does make intuitive sense to allow such dependencies. I believe it was ruled out only due to difficulties with building.

I can imagine it was perhaps also disallowed to discourage ppl from using transitive dependency declarations. If the 'contents' of a metapackage changes (ie: it's `run_depend`s or `exec_depend`s are changed), dependants could suddenly find themselves in a situation where there dependencies are no longer present, even though they didn't change anything.

**Comment by jbohren** [comment]
On looking at this a little closer, it looks like `catkin_make` and `catkin_make_isolated` both *allow* `<exec_depend>` on metapackages, but do not actually use them to define the build order, they just ignore them. The fact that this has been working for people is just lucky (or they've actually been building against other versions installed to their systems).

Since there's nothing in `catkin_make` or `catkin_make_isolated` preventing people from doing this, I propose we include metapackages in dependency resolution so that it does what the user is _trying_ to do, but warn the user loudly if we do.

@wjwwood What do you think about that?

**Comment by gavanderhoorn** [comment]
Is it a good idea to allow this just because `catkin_make` doesn't error out at the moment? Both [REP-127 - \<metapackage/>](http://www.ros.org/reps/rep-0127.html#metapackage) and [REP-140 - \<metapackage/>](http://www.ros.org/reps/rep-0140.html#metapackage) state (non-meta) packages are not allowed to depend on metapackages. There will probably be some flack if `catkin_tools` starts enforcing this, but it would seem like an opportunity to do so?

**Comment by jbohren** [comment]
> Is it a good idea to allow this just because catkin_make doesn't error out at the moment?

I think enough stuff is changing that we don't need `catkin_tools` to start enforcing this , and we could switch this from a warning to an error with the 1.0.0 release.
