### ISSUE TITLE
catkin build abandons packages that depend on a metapackage

### ISSUE THREAD

**Issue by rhaschke** [catkin/catkin_tools#370]
I have a package that declares a `run dependency`  to a metapackage:
` ` `xml
<run_depend>ros_controllers</run_depend>
` ` `
However, catkin build denies to build that one, due to the metapackage being supposedly unknown:
` ` `
[build] Found '79' packages in 0.0 seconds.                                    
Abandoned <<< sr_edc_controller_configuration                 [ Depends on unknown jobs: ros_controllers ]
` ` `

This worked in catkin tools before 4.0.
Removing the run dependency, fixes the problem. But that's obviously a hack.

### System Info
* Operating System: Linux 3.13.0-86-generic #130-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
* Python Version: Python 2.7.6
* Version of catkin_tools: 
` ` `catkin_tools 0.4.2 (C) 2014-2016 Open Source Robotics Foundation
catkin_tools is released under the Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
---
Using Python 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
` ` `
* ROS Distro: indigo

**Comment by gavanderhoorn** [comment]
I think this is a duplicate of #366?

**Comment by rhaschke** [comment]
It's indeed related to #366. However, #366 discusses a **build** dependency to a meta package, which is forbidden according to [REP-140](http://www.ros.org/reps/rep-0140.html#metapackage).
Here, I have defined a **run** dependency, which shouldn't affect catkin build at all. This is a bug to be fixed!

**Comment by gavanderhoorn** [comment]
Hm. You're right this is about a `run_depend`, but the way I interpret REP-140 is that depending on a metapackage is never allowed, not even for `run_depend`encies, *except* in the case of metapackages (so metapackages are allowed to depend on metapackages).

You're right that it isn't explicitly stated in the REP though.

**Comment by rhaschke** [comment]
Some side thought: If metapackages cannot be used at all to pull in transitional dependencies, doesn't that render metapackages useless? Because, then I need to specify all individual dependencies anyway, thus loosing the benefit of the metapackage grouping (some of) them.

In any case, catkin tools shouldn't succeed when abandoning packages. Using catkin tools in our CI system, we thought that everything is fine. But actually the abandoned package was missing.

**Comment by jbohren** [comment]
> Some side thought: If metapackages cannot be used at all to pull in transitional dependencies, doesn't that render metapackages useless? Because, then I need to specify all individual dependencies anyway, thus loosing the benefit of the metapackage grouping (some of) them.

As I understand it, they're only meant for distribution, not source compilation. Frankly I think that the metapackage dependencies and the general model of dependency composition is not well-defined. Like I think I said elsewhere, I don't have a problem with including metapackages in the dependency tree, but it should inform the user that this isn't kosher. 

> In any case, catkin tools shouldn't succeed when abandoning packages. Using catkin tools in our CI system, we thought that everything is fine. But actually the abandoned package was missing.

Yeah we should fix that soon. You wouldn't have a moment to add a test case in a PR that breaks that, would you?

**Comment by rhaschke** [comment]
> Yeah we should fix that soon. You wouldn't have a moment to add a test 
> case in a PR that breaks that, would you?
>
Actually, I don't have the time currently. I'm lacking behind my own 
schedule heavily.

**Comment by jbohren** [comment]
>> Yeah we should fix that soon. You wouldn't have a moment to add a test 
>>  case in a PR that breaks that, would you?
>
> Actually, I don't have the time currently. I'm lacking behind my own 
schedule heavily.

No worries, I'll add it in when I get a chance, then.

**Comment by wjwwood** [comment]
As far as I know, there was never an intention to allow a normal package to have any kind of a dependency on a metapackage. They were just designed to have a replacement for stacks are the debian level, i.e. so you can do `sudo apt-get install ros-foo-desktop-full`. Since metapackages cannot pass along include directories or linker flags or anything like that you are relying on implicit dependencies. That doesn't follow the principal of "include what you use". Basically if you use something directly you should depend on it directly. In the case of cmake, if you `find_pacakge(... foo)` then you should `<build_depend>foo</build_depend>` in you `package.xml`. And if you link against a library in `foo` you should have a run depend on it. You should not just put a dependency on `metafoo` and use `foo` as if you depended on it.

The only time a transitive dependency makes sense is if the dependency is needed by something exported by the package (a header or executable or script). For example, if `bar` provided a header which uses a header from `foo` then it would be ok to just depend on `bar`. But you should then also only `find_package(... bar)` and not also do `find_package(... foo)` anywhere. Also, if you include the header from `foo` directly you should depend on `foo` and `find_package(... foo)` yourself (even though `bar` brings it in transitively). This is because `foo` should be treated as an implementation detail of `bar` and in the future `bar` might drop `foo` as a transitive dependency then your package would be broken.

If you make `bar` a metapackage the example just breaks down because metapackages cannot have any substantial content (by design) and therefore they cannot export anything that would require a transitive dependency.

Any time that has worked in the past (depending on a metapackage from a package), would be a bug in my opinion. @dirk-thomas can you confirm or deny this?

**Comment by dirk-thomas** [comment]
Fully agreeing. This is how metapackages are designed.

**Comment by rhaschke** [comment]
Understand. We already triggered a fix in Shadow Robot's upstream packages. Thanks for this great explanation.
@jbohren What remains, is to return an error code in catkin build, when packages were abandoned.
