### ISSUE TITLE
Including devel/.private folders is done with -I, which is causing warnings in the build.

### ISSUE THREAD

**Issue by jeffeb3** [catkin/catkin_tools#446]
[//]: # (Thank you for reporting an issue for catkin_tools!)

[//]: # (Please fill out the details below so that your issue can be resolved quickly!)
[//]: # (If you want to suggest a feature or start a discussion, feel free to delete them.)

### System Info

* Operating System: Ubuntu 16.04
* Python Version: 2.7.12
* Version of catkin_tools: 0.4.4
* ROS Distro: kinetic

### Build / Run Issue

[//]: # (If you are migrating from catkin_make, please follow the migration guide:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/migration.html)

[//]: # (Please also check for solved issues here:)
[//]: # (http://catkin-tools.readthedocs.org/en/latest/troubleshooting.html)

[//]: # (And check for open issues here:)
[//]: # (https://github.com/catkin/catkin_tools/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

[//]: # (If you have an issue building and running code, please verify the following:)

* [x] Works with `catkin_make`
* [ ] Works with `catkin_make_isolated --merge`
* [ ] Works with `catkin build`
* [ ] Works with `catkin build -p1`
* [ ] I did  not `read this`

### Expected Behavior

[//]: # (Please describe what you expected or think should happen.)
The dynamic reconfigure headers should be included with -isystem, thus making their shadow variable problems not be a warning to me.

### Actual Behavior

[//]: # (Please describe what actually happens.)

[//]: # (Please put long CLI output into Gists: http://gist.github.com)
[//]: # (Use `VERBOSE=1 catkin build -p1 -v` for verbose output)
[//]: # (Please post `logs` directory if available.)

I'm generating dynamic reconfigure header files using `generate_dynamic_reconfigure_options`.

I have `-Wshadow -Werror` enabled, which warns for shadow variables. 

In catkin-tools:
Dynamic reconfigure creates a header file in devel/.private/include/package_name/, and includes it with a `-I/path/to/devel/.private/include/package_name/`. This ends up with warnings, which become errors.

In catkin_make:
Dynamic reconfigure creates a header file in devel/include/package/ folder, which is included with `-iisystem /path/to/devel/include/package_name/`.

Dynamic reconfigure shouldn't have shadow warnings, but that's a different bug I'm going to take up with them. I should be able to focus my warnings on my code, and catkin-tools is breaking that.

### Steps to Reproduce the Issue

[//]: # (Please give a series of command-line commands which cause the problem.)
[//]: # (Include a checkout URI for the workspace so that we can reproduce the issue.)
[//]: # (If we can't reproduce it on our own machines, we can't fix it!)

In my project's CMakeLists.txt:
```bash
include_directories(
    include 
    SYSTEM ${catkin_INCLUDE_DIRS}
)
```

And through a complicated set of cmake files, I'm adding these flags to each targets COMPILE_FLAGS:
"-Wall -Wempty-body -Wshadow -Wextra -Wno-unused-parameter -Werror".

Then I have some code using dynamic reconfigure:
```bash
generate_dynamic_reconfigure_options(
  cfg/parameters.cfg
)
```

### Possible solution

Can we just change the code that includes the .private folders to use -isystem?

**Comment by wjwwood** [comment]
> Can we just change the code that includes the .private folders to use -isystem?

This is not controlled by `catkin_tools`. That is a choice of the packages being built.

Also I can only recommend against using `-isystem` anywhere, due to issues we've run into in the past, for example: https://github.com/ros/rosdistro/issues/12783 (and others you can find by Google-ing around).

If your purpose is to suppress the warnings, then I recommend you use the GCC (and clang has this too) diagnostic pragmas to suppress the warnings at the point where you include the headers in your source files, see:

https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html

I do not believe that this is a `catkin_tools` issue (only its difference in behavior from `catkin_make` exposes this issue). Therefore, I'm going to close this. Feel free to continue the discussion here and I can reopen it if necessary.

**Comment by jeffeb3** [comment]
Sorry for the delayed response. Thank you for the prompt one.

OK, so -isystem has some problems. I'm not sure I like the #pragma approach, although I appreciate a thoughtful suggestion. 

If I wanted to go against your recommendation, and include that file via isystem, do I have the ability to control that in my package's CMakeLists.txt? It seems like it isn't in my control. From my perspective, it looks like catkin-tools is configuring that include (the .private folder).

**Comment by wjwwood** [comment]
Whether or not you use `-isystem` is completely up to your package. See the `SYSTEM` directive in the cmake `include_directories` macro:

https://cmake.org/cmake/help/v3.0/command/include_directories.html

**Comment by wjwwood** [comment]
Also, this SO, which is more direct to the point than the cmake docs:

http://stackoverflow.com/a/3371528/671658

**Comment by jeffeb3** [comment]
I use that include_directories macro:

```bash
include_directories(
    include 
    SYSTEM ${catkin_INCLUDE_DIRS}
)
```

The `include` is adding the -I for the headers in this package, but that single header file from dynamic reconfigure ends up in:

`devel/.private/<package>/include/<package>/`

That folder isn't in my include_directories, I'm assuming that catkin-tools adds it somewhere.

**Comment by wjwwood** [comment]
That is the include directory for `<package>`, that's what `include` gets expanded to when exported by that package, so that's how it gets into your `catkin_INCLUDE_DIRS`. This is a function of `caktin`'s auto-generated CMake config file. It doesn't really have anything to do with `catkin_tools`. `catkin_tools` is responsible for the folder structure, but not how the include direct is exported.
