### ISSUE TITLE
Changes between 0.6.x (Trusty) and 0.7.x (Xenial)?

### ISSUE THREAD

**Issue by wxmerkt** [catkin/catkin_tools#463]
### System Info

* Operating System: Xenial and Trusty
* Python Version: 2.7.12 and 2.7.5
* Version of catkin_tools: 0.4.4 - ros-{version}-catkin respectively: 0.7.6 and 0.6.19
* ROS Distro: kinetic and indigo

### Build / Run Issue

* [x] Works with `catkin build` on Trusty with catkin_tools (catkin 0.6.19)
* [ ] Works with `catkin build` on Xenial with catkin_tools 0.4.4 (catkin 0.7.6)

### Expected and Actual Behavior

We are creating a header via custom CMake logic at configuration time, which gets successfully installed into ``devel/include/[package]/OurCustomHeader.h``. Requiring [package] via ``find_package(catkin REQUIRED COMPONENTS [package])`` in another project and outputting ``${catkin_INCLUDE_DIRS}`` includes ``devel/include/``. Note, our workspace does not use an install space (catkin config --no-install).

Compiling the same code unter Xenial/Kinetic, we get an error message that the custom header could not be found - this is due to the ``${catkin_INCLUDE_DIRS}`` only capturing ``src/[package]/include``.

Thus, has there been any change regarding the paths picked up into INCLUDE_DIRS between 0.6.x and 0.7.x? (I didn't see anything in CHANGELOG.rst newer than 0.4.x)

**Comment by wjwwood** [comment]
The latest version of `catkin_tools` is `0.4.4`. So when you say `on Xenial with catkin_tools 0.7.6` I don't know what you mean. Also the `catkin_tools` is not tied to the ROS version. It's version is the same whether you're using Indigo or Kinetic.

I think you're confusing `catkin_tools` (just the `catkin` command line tool) with `catkin` which is the cmake logic which can be used with or without these tools:

https://github.com/ros/catkin

Can you confirm this issue is present or not with `catkin_make_isolated`? If it fails in the same way with `catkin_make_isolated` then this should probably be closed and reopened on `catkin`'s issue tracker.

**Comment by wxmerkt** [comment]
Apologies - opened it on the wrong issue tracker!

**Comment by wjwwood** [comment]
No worries, if it ends up being a problem introduced by using `catkin_tools` I can reopen this.
