### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by niosus** [catkin/catkin_tools#507]
Hey guys. I value the work you've done so far a lot. Catkin tools has become a tool of choice in our lab as a way to manage dependencies of our projects without relying on a server-based package manager as well as a way to manage our builds. And all this not relying on ROS.

However, I see that there has been little to none activity in the latest time in the code as well as in issues discussions. There is a bunch of fixes that have already landed into master but have not been released as of now (last release a year ago).

As a maintainer of I understand that maintaining an open source project takes its toll and time is not always there. But this is a very valuable tool and I would hate to see it die.

So there is a bunch of questions I would like to ask: 
- Is this project dead? 
- Is there anything coming to replace it that you're working on? 
- Do you need help maintaining this project if you don't consider it dead?

**Comment by wjwwood** [comment]
> Hey guys. I value the work you've done so far a lot. Catkin tools has become a tool of choice in our lab as a way to manage dependencies of our projects without relying on a server-based package manager as well as a way to manage our builds.

Glad to hear it.

> There is a bunch of fixes that have already landed into master but have not been released as of now (last release a year ago).

That's pretty much solely my fault. I didn't have time to do it at the time and it has slipped down the priority queue for me over and over (people keep pointing it out). One of the reasons it was released about a year ago is because that's when Lunar was released, and I tend to spend the most time on my ROS related projects (this, rviz, rosdep, wstool/rosinstall/vcstools, etc...) around release time. So I'll probably get to some of the stuff on this repository soon in preparation for Melodic, but that's never certain.

> Is this project dead?

I hope not. As pretty much the sole maintainer here the lack of activity in releases and pr's merged is definitely my fault, but I don't consider it dead because I don't intend to never spend time on it again, I just haven't time to do so over the last year. But I guess it depends on your definition of dead.

Part of the problem is also that I default to inaction on pr's and new releases, simply because a poorly tested pr or release usually creates more work than doing it properly, and if I don't have time to do it properly in the first place, better not to move at all. I know many people will not agree with this, but that's what I've been doing in an environment of scarce resources for the project.

> Is there anything coming to replace it that you're working on?

I'm not.

> Do you need help maintaining this project if you don't consider it dead?

Yes. No one has asked yet (that I remember), but I'm definitely open to sharing responsibility.

However, because catkin_tools is used by so many I won't let just anyone become a maintainer. I need to know they won't make rash changes and releases and further more that I won't have to police their behavior (again more that I don't have time for in the first place). So I need to have some experience working with them or have some evidence of their work on other projects.

So if you, or anyone else is interested in becoming a maintainer, let me know and I'll try to allocate more time to make that happen.

---

I'm also going to close this, since it's more a discussion than a technical issue that needs a pr to solve. But feel free to continue the discussion here. I can reopen it if necessary.

**Comment by mikepurvis** [comment]
I may be able to commit some time to formal maintainership responsibilities.

**Comment by dirk-thomas** [comment]
I would like to add that the idea of a "universal" build tool which works for both - ROS 1 and ROS 2 (and maybe even non-ROS packages) - is currently being re-evaluated. The topic had been dropped about a year ago - see the former [design document](http://design.ros2.org/articles/build_tool.html) - since no resources were available for the expected effort.

The goal of having a single tool serving multiple use cases will hopefully broaden the user base which then will also broaden the contributions. Currently in many cases we are not working on new features for the various build tools since they would be beneficial for all existing tools but we don't want to duplicate the effort. That situation has led to this kind of "stale" situation. Neither `catkin_tools` nor `ament_tools` have received much attention in the past one and a half years.

Hopefully that is going to change soon. I will post any results of the re-evaluation in the coming weeks.

**Comment by niosus** [comment]
Hey everyone. Thanks for a very open reply and for all the info.

@wjwwood I completely understand your point about the PRs. It really takes a lot of time to understand someone else's code and to find out if it is possible to integrate into the current codebase maintaining a decent level of quality. I have a different opinion on an optimal time-saving strategy for issues and PRs, i.e. that you can enforce the granularity and size of PRs and quality of issues relatively easily by closing ones that don't correspond to the intended standard, which will make it manageable to review them, but I also understand your point on this.

As for the help with maintaining, I would love to offer my help, but even if you would consider it, I am struggling as it is to keep a good level of maintenance on my own open source projects, so, for now, I would not be comfortable taking additional responsibilities. I do hope that more people will volunteer now that we have opened this discussion.

@dirk-thomas if I can add my 5 cents, I wanted to point out that my perceived issue with multiple build systems that I've been using in ROS for the last 5-6 years is a lack of continuity between them. They were always new and always doing something not really what I expected them to do, e.g. merging all projects into one big cmake file breaking dependency priorities. Catkin tools was the first project that could do everything that I wanted it to do in ROS environment and then allowed to adopt it for non-ROS development too. In addition to that the plugin structure to add verbs is extremely valuable as it allows to add more functionality to catkin tools without changing the actual code in this project. Judging from the document you linked you have reached the same conclusions and one of the options is to build up catkin_tools. It also supports most of the extension points out of the box. If we drop the point to support packages with no `package.xml` file, then it already performs nearly everything needed and is time tested.

Thanks again for this answer and I am glad to hear that the project is not dead, merely tired :)

**Comment by dirk-thomas** [comment]
@niosus There is a clear separation between build tool (e.g. `catkin_make(_isolated)`, `catkin tools`, `ament tools`) and build systems (the CMake API of `catkin`, `ament_cmake`, `CMake`, `setuptools`, `Make`). In ROS 1 the only build system transition was from `rosbuild` to `catkin`. While certainly "painful" it has paid off - many use cases wouldn't be possible without it. In ROS 2 `ament_cmake` is pretty much an evolution of `catkin` based on the feedback we got in ROS 1 and what we learned from using `catkin` for several years (see [ament design doc](http://design.ros2.org/articles/ament.html)).

> catkin_tools ... already performs nearly everything needed and is time tested.

Well, I could name several things it currently doesn't address / handle or could be improved (e.g. Windows support). But let's not get ahead of that discussion :wink:

**Comment by niosus** [comment]
Ugh, Windows :) Yeah, you definitely know so much more about the ups and downs of all the tools, so I am shutting up right now :) My evidence is purely anecdotal. `catkin_tools` happens to fill my boxes, but yeah, I can see how it have many shortcomings in other domains.

**Comment by dirk-thomas** [comment]
> I am shutting up right now

No need to do that :wink: Any feedback is very welcome.

It makes total sense: since ROS 1 doesn't really aim to support Windows why would catkin tools put effort into supporting that platform. Same for packages without manifest files. It is doing what it is used for - and it is doing that well :+1:

**Comment by NikolausDemmel** [comment]
> Hopefully that is going to change soon. I will post any results of the re-evaluation in the coming weeks.

@dirk-thomas Not sure if you were implying that already anyway, but could you please link to that discussion and/or results in this issue when the time comes (or else, where should we be looking?). Thanks.

**Comment by dirk-thomas** [comment]
> could you please link to that discussion and/or results in this issue when the time comes

Absolutely!

**Comment by mikepurvis** [comment]
A few other cents to throw in here—

First, with a minimal amount of effort, I was able to get catkin_tools as it exists today building ament_cmake and ament_python packages (basically making new build-type plugins for those package types, one of which passes through to "cmake" and the other to [catkin_tools_python](https://github.com/mikepurvis/catkin_tools_python)). And catkin_tools as written today works fine under Python 3. So we should be clear that a rewrite is not at all required to support ROS 2—we're primarily talking about a new project motivated by:

- Architectural cleanup that is possible by supporting only Python 3 and its native async capabilities, and,
- First class Windows support.

I can appreciate that the second item is a tentpole feature for ROS 2, despite not being personally interesting to me.

The second concern is that Clearpath's build infrastructure is now tied to some kind of esoteric corners of c_t, in particular the `--isolate-install` flag, log management, etc. It would be important to us that a new package avoid excluding or explicitly designing-out these features as part of an effort to streamline or simplify.

**Comment by niosus** [comment]
@dirk-thomas thanks for taking feedback seriously :) 
I do not have a userbase as ROS has, but developing a wildly used tool has taught me to now expect that I can anticipate all the use cases. People will find a way to use your tool in the ways that you did not imagine. That is my main argument in the direction of trying to keep as much as possible if it does not have huge shortcomings. I also know the urge to rewrite things "in a right way". It is usually more exciting and the idea is to build a beautiful architecture, but in these cases, I tend to remind myself that "done is better than perfect". Catkin tools is a fairly mature project. I believe it is underrated as it is now. It does what is advertised and allows to add things that were probably not anticipated at the start of the project, like [fetch](https://github.com/Photogrammetry-Robotics-Bonn/catkin_tools_fetch) verb for example. I have unfortunately no knowledge how far in development within ROS2 you are and what tool have you guys been working on, but it would be a shame to throw away all the developments here.

@mikepurvis I wonder how difficult it is actually to support windows for a tool like this. I have some experience with tooling for all 3 major platforms and from my perspective as long as the underlying tool, e.g. cmake is cross-platform, which it is then we just have to care about consistently using `os.path` and minor platform-dependent obscurities. As for python 3 and the architectural cleanup, `trollius` and `asyncio` have fairly similar interfaces and exactly the same idea behind them, so there should not be much to cleanup. 

As a side note, is there a place where these things get discussed? It seems a bit weird to pollute this thread with this, relatively, off-topic discussion.

**Comment by wjwwood** [comment]
> First, with a minimal amount of effort, I was able to get catkin_tools as it exists today building ament_cmake and ament_python packages (basically making new build-type plugins for those package types, one of which passes through to "cmake" and the other to catkin_tools_python).

Can you share that (the ament part)?

> @mikepurvis I wonder how difficult it is actually to support windows for a tool like this.

Not difficult, but perhaps time consuming. I originally added support for Windows in ROS 2:

- https://github.com/ament/ament_tools/pull/19

Which is small, but it had quite a few changes to the "setup" files for which there needs to be `.bat` alternatives on Windows:

- https://github.com/ament/ament_package/pull/6

And it of course affects the thing your building as well, so if supporting catkin on Windows natively is a goal (might be an anti-goal, dunno) then you would need to perhaps make changes to it as well, here's the equivalent for ament:

- https://github.com/ament/ament_cmake/pull/3

**Comment by wjwwood** [comment]
> As a side note, is there a place where these things get discussed? It seems a bit weird to pollute this thread with this, relatively, off-topic discussion.

I think here is ok too, but for public discussions, this design doc is the closest place I'm aware of:

https://github.com/ros2/design/pull/115

Or perhaps a new pr or issue for discussion there. Honestly, discourse is the probably the right place until you start to discuss actual technical changelogs or a design document. Maybe @dirk-thomas can suggest a location since he's spearheading that design doc/topic.

**Comment by wjwwood** [comment]
@mikepurvis said:

> I may be able to commit some time to formal maintainership responsibilities.

That would be great, I didn't ask you directly because I figured you were already busy helping with `ros/ros_comm`. I'll give you permissions on this repository and let you review and merge pr's if you like. I think I still need to do releases due to needing push permissions to our apt repositories.

**Comment by DLu** [comment]
So it's been [19 months](https://github.com/catkin/catkin_tools/releases) since a release. I just went through and was about to make a PR to fix #470/#500 but I'm relatively certain its already been fixed....it just hasn't been released. 

Is there anything people who are not @wjwwood can do to help facilitate a new release?
