### ISSUE TITLE
Why end with many "Abandoned" error lines instead of the actual errors?

### ISSUE THREAD

**Issue by v4hn** [catkin/catkin_tools#512]
I started using catkin_tools recently, and apparently lots of thoughts went in there from a workspace maintainers' point of view.
But when I actually develop code in a non-minimal workspace and something fails to build in the middle of the build process, at the end of the console output I get tons of lines saying
```
Abandoned <<< XYZ                                 [ Unrelated job failed ]
```
instead of the actual build errors, or even the name of the failed package.
Together with the typical length of C++ error messages this easily exceeds scrollback on my systems
and I end up using combinations of `catkin build`, `catkin build >/dev/null`, `catkin build 2>&1 | less` to build my workspace.
It would be very nice for usability if at the end of the output (1.) there would the error log of the failed package, possibly only the first few lines, or (2.) a line saying "package xyz failed to build. Look here for the full error log: /logfile". Another alternative would be to just stop processing after the first error.
Of course something like this could be optional.

What would you prefer upstream?

**Comment by NikolausDemmel** [comment]
I second that this would be useful, at least as an option, but maybe even default. Reiterating (part of) the error log for failed packages, listing the corresponding log files for easy inspection should both be helpful. Note that with parallel builds there might be more than one failed package.

I have been slightly annoyed about this scrolling to get to the error message as well. However, it hasn't really bothered me that much for daily development, since:
* mostly I import the build directories for packages that I develop into QtCreator anyway and run make from there
* error messages for parallel builds are often hard to read anyway, so my usual pattern in case of a failed package to follow a build error with something like `catkin build -j1 -i -v --no-deps  <failed_pkg>`.

**Comment by v4hn** [comment]
> `catkin build -j1 -i -v --no-deps  <failed_pkg>`

If you know the name of the failed package already, that's possible, yes.
But the output doesn't say that either. :-)

**Comment by NikolausDemmel** [comment]
> If you know the name of the failed package already, that's possible, yes.

Yes exactly, for this one you currently still have to scroll up to find the failed package.

**Comment by racko** [comment]
You should check out the `--summarize` option:

```
  --summarize, --summary, -s
                        Adds a build summary to the end of a build; defaults
                        to on with --continue-on-failure, off otherwise
```

**Comment by wjwwood** [comment]
The `--summarize` option was basically the compromise, because I also wanted it to not print out abandoned packages due to the spam in large workspaces, but I believe we (@jbohren and I) finally agreed to instead summarize things with `--summarize`.  I can't find our discussion about it on github, it might have been just in a video call or something. We did a lot of those during his big refactoring.

**Comment by v4hn** [comment]
I tried to work with `--summarize` for a while, but it does not solve the problem, as hinted by @racko already.

In many cases it looks like this when I use it and encounter problems:
![abandoned](https://user-images.githubusercontent.com/680358/40536884-c7720960-600d-11e8-850d-b03b4c7d2268.png)

Obviously this is not helpful.

Another, minor, problem is that meta-packages are marked as `ignored` in a different color than success, which becomes confusing when there are also *actually ignored* packages in the workspace.

So to reiterate my initial question:
I would very much like to have an option to make `catkin build` list failed packages and possibly (part of) their error log in the very end. What kind of solution would you be willing to merge upstream?
Personally I would be more than happy with something similar to
```
cat <first_failed_package_error.log>
echo "package <first_failed_package_name> failed to build"
```

**Comment by v4hn** [comment]
@timonegk I just started compiling big ros one workspaces again and hit this issues again.
Could you comment here or think up a solution you would like?
