### ISSUE TITLE
Is Windows supported?

### ISSUE THREAD

**Issue by andreabedini** [catkin/catkin_tools#554]
(Apologies for ignoring the issue template)

I can't seem to infer it from the documentation, is catkin meant to work on windows or not at all? This is a genuine question, I see someone mentioning [ROS on Widows](https://github.com/ms-iot/ROSOnWindows/blob/master/GettingStarted/UsingROSonWindows.md) but catkin seems to import `termios` and `fcntl` which are Unix specific modules. I have tried to hack my way around it but I'd like to know if there's light at the end of the tunnel :-)

Thanks.

**Comment by mikepurvis** [comment]
I don't believe `catkin_tools` has ever supported Windows, officially or otherwise. This was actually cited as ones of its shortcomings in rationalizing the creation of its successor, `colcon`. See: https://design.ros2.org/articles/build_tool.html

I would suggest trying that: https://colcon.readthedocs.io/en/released/user/quick-start.html#build-ros-1-packages

**Comment by andreabedini** [comment]
All clear, thank you @mikepurvis
